server:
  port: 6060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-catalogo-service
          uri: lb://ms-catalogo-service
          predicates:
            - Path=/producto/**, /categoria/**
        - id: ms-catalogo-cliente
          uri: lb://ms-catalogo-cliente
          predicates:
            - Path=/cliente/**
        - id: ms-pedido-service
          uri: lb://ms-pedido-service
          predicates:
            - Path=/pedido/**

